name: Commit date to master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  commit_history:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: get commit history
        uses: nisargshah1410/git_com@v1.7
        with:
          github_handle: NisargShah1410
          repository: git_com
          
