
name: Trigger and wait action test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: NisargShah1410
          repo: graph_act
          workflow_file_name: pull_req.yml
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          propagate_failure: false
          trigger_workflow: true
